=== EmilioAngu2003/DAM/DAM_02/LMSGI/XML/XSD/Hoja 4/ejercicio06/biblioteca.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="biblioteca">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="libro" type="tipo-libro" minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="tipo-libro">
        <xs:sequence>
            <xs:element name="codigolibro" type="xs:string"/>
            <xs:element name="titulo" type="xs:string"/>
            <xs:element name="editorial" type="xs:string"/>
            <xs:element name="edicion" type="xs:string"/>
            <xs:element name="ISBN" type="xs:string"/>
            <xs:element name="numeropaginas" type="xs:string"/>
            <xs:element name="autor" type="xs:string"/>
        </xs:sequence>
        <xs:attribute name="area" type="xs:string"/>
    </xs:complexType>

</xs:schema>

=== EmilioAngu2003/DAM/DAM_02/LMSGI/XML/XSD/Hoja 4/ejercicio06/biblioteca.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="hoja.css"?>
<biblioteca xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="biblioteca.xsd">
    <libro area="ciencias">
        <codigolibro>12345</codigolibro>
        <titulo>El mundo de los anfibios</titulo>
        <editorial>Rama</editorial>
        <edicion>1</edicion>
        <ISBN>234567CD</ISBN>
        <numeropaginas>300</numeropaginas>
        <autor>Antonio Del RÃ­o</autor>
    </libro>
    <libro area="literatura">
        <codigolibro>12346</codigolibro>
        <titulo>El Quijote</titulo>
        <editorial>Mc Graw Hill</editorial>
        <edicion>4</edicion>
        <ISBN>123123AB</ISBN>
        <numeropaginas>3000</numeropaginas>
        <autor>Cervantes</autor>
    </libro>
    <libro area="literatura">
        <codigolibro>12346</codigolibro>
        <titulo>El Quijote</titulo>
        <editorial>Mc Graw Hill</editorial>
        <edicion>4</edicion>
        <ISBN>123123AB</ISBN>
        <numeropaginas>3000</numeropaginas>
        <autor>Cervantes</autor>
    </libro>
    <libro area="literatura">
        <codigolibro>12346</codigolibro>
        <titulo>El Quijote</titulo>
        <editorial>Mc Graw Hill</editorial>
        <edicion>4</edicion>
        <ISBN>123123AB</ISBN>
        <numeropaginas>3000</numeropaginas>
        <autor>Cervantes</autor>
    </libro>
    <libro area="literatura">
        <codigolibro>12346</codigolibro>
        <titulo>El Quijote</titulo>
        <editorial>Mc Graw Hill</editorial>
        <edicion>4</edicion>
        <ISBN>123123AB</ISBN>
        <numeropaginas>3000</numeropaginas>
        <autor>Cervantes</autor>
    </libro>
    <libro area="literatura">
        <codigolibro>12346</codigolibro>
        <titulo>El Quijote</titulo>
        <editorial>Mc Graw Hill</editorial>
        <edicion>4</edicion>
        <ISBN>123123AB</ISBN>
        <numeropaginas>3000</numeropaginas>
        <autor>Cervantes</autor>
    </libro>
    <libro area="literatura">
        <codigolibro>12346</codigolibro>
        <titulo>El Quijote</titulo>
        <editorial>Mc Graw Hill</editorial>
        <edicion>4</edicion>
        <ISBN>123123AB</ISBN>
        <numeropaginas>3000</numeropaginas>
        <autor>Cervantes</autor>
    </libro>
    <libro area="literatura">
        <codigolibro>12346</codigolibro>
        <titulo>El Quijote</titulo>
        <editorial>Mc Graw Hill</editorial>
        <edicion>4</edicion>
        <ISBN>123123AB</ISBN>
        <numeropaginas>3000</numeropaginas>
        <autor>Cervantes</autor>
    </libro>
    <libro area="literatura">
        <codigolibro>12346</codigolibro>
        <titulo>El Quijote</titulo>
        <editorial>Mc Graw Hill</editorial>
        <edicion>4</edicion>
        <ISBN>123123AB</ISBN>
        <numeropaginas>3000</numeropaginas>
        <autor>Cervantes</autor>
    </libro>
    <libro area="literatura">
        <codigolibro>12346</codigolibro>
        <titulo>El Quijote</titulo>
        <editorial>Mc Graw Hill</editorial>
        <edicion>4</edicion>
        <ISBN>123123AB</ISBN>
        <numeropaginas>3000</numeropaginas>
        <autor>Cervantes</autor>
    </libro>
</biblioteca>
