=== EmilioAngu2003/DAM/DAM_02/LMSGI/XML/DTD/Hoja 3/ejecicio02/DTDexterno/alumnos.dtd
<!ELEMENT alumnos (alumno*)>
<!ELEMENT alumno (nombre, apellidos, domicilio, telefono+)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellidos (#PCDATA)>
<!ELEMENT domicilio (#PCDATA)>
<!ELEMENT telefono EMPTY>
<!ATTLIST telefono numero CDATA #REQUIRED>

=== EmilioAngu2003/DAM/DAM_02/LMSGI/XML/DTD/Hoja 3/ejecicio02/DTDexterno/alumnos.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE alumnos SYSTEM "alumnos.dtd">
<alumnos>
    <alumno>
        <nombre>Juan</nombre>
        <apellidos>Pérez</apellidos>
        <domicilio>Calle A, Ciudad</domicilio>
        <telefono numero="123456789"/>
    </alumno>
    <alumno>
        <nombre>Maria</nombre>
        <apellidos>Gómez</apellidos>
        <domicilio>Calle B, Ciudad</domicilio>
        <telefono numero="987654321"/>
    </alumno>
</alumnos>
