=== EmilioAngu2003/DAM/DAM_02/LMSGI/XML/XSD/Hoja 4/ejercicio02/vehiculos.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="vehiculos">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="vehiculo" minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="vehiculo">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="nombre" type="xs:string" minOccurs="1" maxOccurs="unbounded"/>
                <xs:element name="modelo" type="xs:string"/>
                <xs:element name="fabricacion" type="elemento-fabricacion"/>
                <xs:element name="versiones" type="elemento-versiones"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="elemento-fabricacion">
        <xs:sequence>
            <xs:element name="inicio" type="elemento-fecha"/>
            <xs:element name="fin" type="elemento-fecha"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="elemento-fecha">
        <xs:sequence>
            <xs:element name="dia" type="xs:string"/>
            <xs:element name="mes" type="xs:string"/>
            <xs:element name="anyo" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="elemento-versiones">
        <xs:sequence>
            <xs:element name="version" type="xs:string" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

</xs:schema>

=== EmilioAngu2003/DAM/DAM_02/LMSGI/XML/XSD/Hoja 4/ejercicio02/vehiculos.xml
<?xml version="1.0" encoding="UTF-8"?>
<vehiculos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="vehiculos.xsd">
    <vehiculo>
        <nombre>Audi </nombre>
        <modelo>R8</modelo>
        <fabricacion>
            <inicio>
                <dia>21</dia>
                <mes>Julio</mes>
                <anyo>2007</anyo>
            </inicio>
            <fin>
                <dia>9</dia>
                <mes>Agosto</mes>
                <anyo>2010</anyo>
            </fin>
        </fabricacion>
        <versiones>
            <version>Coup√©</version>
            <version>GT</version>
            <version>R8 V12 TDI Le Mans</version>
            <version>Targa o Roadster</version>
            <version>Spyder</version>
        </versiones>
    </vehiculo>
</vehiculos>
