<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE alumnos [
    <!ELEMENT alumnos (alumno*)>
    
    <!ELEMENT alumno (nombre, apellidos, domicilio, telefono+)>
    
    <!ELEMENT nombre (#PCDATA)>
    
    <!ELEMENT apellidos (#PCDATA)>
    
    <!ELEMENT domicilio (#PCDATA)>
    
    <!ELEMENT telefono EMPTY>
    <!ATTLIST telefono numero CDATA #REQUIRED >
]>

<alumnos>
    <alumno>
        <nombre>Juan</nombre>
        <apellidos>Pérez</apellidos>
        <domicilio>Calle A, Ciudad</domicilio>
        <telefono numero="123456789"/>
    </alumno>
    <alumno>
        <nombre>Maria</nombre>
        <apellidos>Gómez</apellidos>
        <domicilio>Calle B, Ciudad</domicilio>
        <telefono numero="987654321"/>
    </alumno>
</alumnos>
